# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'MIIL_DETECTION_DIRECTION_VINO_GUI.ui'
##
## Created by: Qt User Interface Compiler version 6.10.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QGroupBox,
    QLabel, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QSizePolicy, QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(782, 473)
        MainWindow.setMinimumSize(QSize(782, 473))
        MainWindow.setMaximumSize(QSize(782, 473))
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox1 = QGroupBox(self.centralwidget)
        self.groupBox1.setObjectName(u"groupBox1")
        self.groupBox1.setGeometry(QRect(10, 10, 211, 61))
        self.pushButton1 = QPushButton(self.groupBox1)
        self.pushButton1.setObjectName(u"pushButton1")
        self.pushButton1.setGeometry(QRect(10, 20, 93, 28))
        self.pushButton2 = QPushButton(self.groupBox1)
        self.pushButton2.setObjectName(u"pushButton2")
        self.pushButton2.setEnabled(False)
        self.pushButton2.setGeometry(QRect(110, 20, 93, 28))
        self.groupBox4 = QGroupBox(self.centralwidget)
        self.groupBox4.setObjectName(u"groupBox4")
        self.groupBox4.setGeometry(QRect(230, 80, 91, 61))
        self.comboBox1 = QComboBox(self.groupBox4)
        self.comboBox1.setObjectName(u"comboBox1")
        self.comboBox1.setGeometry(QRect(10, 20, 71, 22))
        self.groupBox9 = QGroupBox(self.centralwidget)
        self.groupBox9.setObjectName(u"groupBox9")
        self.groupBox9.setGeometry(QRect(10, 220, 761, 61))
        self.lineEdit4 = QLineEdit(self.groupBox9)
        self.lineEdit4.setObjectName(u"lineEdit4")
        self.lineEdit4.setEnabled(False)
        self.lineEdit4.setGeometry(QRect(10, 20, 641, 20))
        self.pushButton6 = QPushButton(self.groupBox9)
        self.pushButton6.setObjectName(u"pushButton6")
        self.pushButton6.setGeometry(QRect(660, 20, 93, 28))
        self.groupBox10 = QGroupBox(self.centralwidget)
        self.groupBox10.setObjectName(u"groupBox10")
        self.groupBox10.setGeometry(QRect(10, 290, 761, 61))
        self.lineEdit5 = QLineEdit(self.groupBox10)
        self.lineEdit5.setObjectName(u"lineEdit5")
        self.lineEdit5.setEnabled(False)
        self.lineEdit5.setGeometry(QRect(10, 20, 641, 20))
        self.pushButton7 = QPushButton(self.groupBox10)
        self.pushButton7.setObjectName(u"pushButton7")
        self.pushButton7.setGeometry(QRect(660, 20, 93, 28))
        self.groupBox3 = QGroupBox(self.centralwidget)
        self.groupBox3.setObjectName(u"groupBox3")
        self.groupBox3.setGeometry(QRect(10, 80, 211, 61))
        self.pushButton4 = QPushButton(self.groupBox3)
        self.pushButton4.setObjectName(u"pushButton4")
        self.pushButton4.setGeometry(QRect(110, 20, 93, 28))
        self.pushButton3 = QPushButton(self.groupBox3)
        self.pushButton3.setObjectName(u"pushButton3")
        self.pushButton3.setEnabled(True)
        self.pushButton3.setGeometry(QRect(10, 20, 93, 28))
        self.groupBox8 = QGroupBox(self.centralwidget)
        self.groupBox8.setObjectName(u"groupBox8")
        self.groupBox8.setGeometry(QRect(10, 150, 761, 61))
        self.lineEdit3 = QLineEdit(self.groupBox8)
        self.lineEdit3.setObjectName(u"lineEdit3")
        self.lineEdit3.setEnabled(False)
        self.lineEdit3.setGeometry(QRect(10, 20, 641, 20))
        self.pushButton5 = QPushButton(self.groupBox8)
        self.pushButton5.setObjectName(u"pushButton5")
        self.pushButton5.setGeometry(QRect(660, 20, 93, 28))
        self.groupBox5 = QGroupBox(self.centralwidget)
        self.groupBox5.setObjectName(u"groupBox5")
        self.groupBox5.setGeometry(QRect(330, 80, 101, 61))
        self.comboBox2 = QComboBox(self.groupBox5)
        self.comboBox2.setObjectName(u"comboBox2")
        self.comboBox2.setGeometry(QRect(10, 20, 81, 21))
        self.groupBox2 = QGroupBox(self.centralwidget)
        self.groupBox2.setObjectName(u"groupBox2")
        self.groupBox2.setGeometry(QRect(230, 10, 541, 61))
        self.lineEdit1 = QLineEdit(self.groupBox2)
        self.lineEdit1.setObjectName(u"lineEdit1")
        self.lineEdit1.setEnabled(False)
        self.lineEdit1.setGeometry(QRect(260, 20, 71, 20))
        self.lineEdit2 = QLineEdit(self.groupBox2)
        self.lineEdit2.setObjectName(u"lineEdit2")
        self.lineEdit2.setEnabled(False)
        self.lineEdit2.setGeometry(QRect(360, 20, 71, 20))
        self.label1 = QLabel(self.groupBox2)
        self.label1.setObjectName(u"label1")
        self.label1.setGeometry(QRect(30, 20, 16, 20))
        self.label_2 = QLabel(self.groupBox2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(130, 20, 16, 20))
        self.checkBox1 = QCheckBox(self.groupBox2)
        self.checkBox1.setObjectName(u"checkBox1")
        self.checkBox1.setGeometry(QRect(10, 20, 31, 16))
        self.checkBox1.setAutoExclusive(True)
        self.pushButton8 = QPushButton(self.groupBox2)
        self.pushButton8.setObjectName(u"pushButton8")
        self.pushButton8.setGeometry(QRect(440, 20, 93, 28))
        self.label_3 = QLabel(self.groupBox2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(240, 20, 16, 20))
        self.lineEdit6 = QLineEdit(self.groupBox2)
        self.lineEdit6.setObjectName(u"lineEdit6")
        self.lineEdit6.setEnabled(False)
        self.lineEdit6.setGeometry(QRect(50, 20, 71, 20))
        self.label_4 = QLabel(self.groupBox2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(340, 20, 16, 20))
        self.lineEdit7 = QLineEdit(self.groupBox2)
        self.lineEdit7.setObjectName(u"lineEdit7")
        self.lineEdit7.setEnabled(False)
        self.lineEdit7.setGeometry(QRect(150, 20, 71, 20))
        self.groupBox6 = QGroupBox(self.centralwidget)
        self.groupBox6.setObjectName(u"groupBox6")
        self.groupBox6.setGeometry(QRect(590, 80, 111, 61))
        self.comboBox3 = QComboBox(self.groupBox6)
        self.comboBox3.setObjectName(u"comboBox3")
        self.comboBox3.setGeometry(QRect(10, 20, 91, 21))
        self.groupBox7 = QGroupBox(self.centralwidget)
        self.groupBox7.setObjectName(u"groupBox7")
        self.groupBox7.setGeometry(QRect(710, 80, 61, 61))
        self.checkBox2 = QCheckBox(self.groupBox7)
        self.checkBox2.setObjectName(u"checkBox2")
        self.checkBox2.setGeometry(QRect(10, 20, 41, 16))
        self.groupBox11 = QGroupBox(self.centralwidget)
        self.groupBox11.setObjectName(u"groupBox11")
        self.groupBox11.setGeometry(QRect(10, 360, 461, 61))
        self.pushButton9 = QPushButton(self.groupBox11)
        self.pushButton9.setObjectName(u"pushButton9")
        self.pushButton9.setGeometry(QRect(260, 20, 93, 28))
        self.pushButton10 = QPushButton(self.groupBox11)
        self.pushButton10.setObjectName(u"pushButton10")
        self.pushButton10.setGeometry(QRect(360, 20, 93, 28))
        self.label_5 = QLabel(self.groupBox11)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(10, 30, 41, 20))
        self.label_6 = QLabel(self.groupBox11)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(130, 30, 51, 20))
        self.comboBox5 = QComboBox(self.groupBox11)
        self.comboBox5.setObjectName(u"comboBox5")
        self.comboBox5.setGeometry(QRect(190, 30, 61, 21))
        self.lineEdit8 = QLineEdit(self.groupBox11)
        self.lineEdit8.setObjectName(u"lineEdit8")
        self.lineEdit8.setEnabled(True)
        self.lineEdit8.setGeometry(QRect(60, 30, 61, 20))
        self.groupBox13 = QGroupBox(self.centralwidget)
        self.groupBox13.setObjectName(u"groupBox13")
        self.groupBox13.setGeometry(QRect(440, 80, 141, 61))
        self.comboBox4 = QComboBox(self.groupBox13)
        self.comboBox4.setObjectName(u"comboBox4")
        self.comboBox4.setGeometry(QRect(50, 20, 81, 21))
        self.checkBox3 = QCheckBox(self.groupBox13)
        self.checkBox3.setObjectName(u"checkBox3")
        self.checkBox3.setGeometry(QRect(10, 20, 51, 16))
        self.groupBox12 = QGroupBox(self.centralwidget)
        self.groupBox12.setObjectName(u"groupBox12")
        self.groupBox12.setGeometry(QRect(720, 360, 51, 61))
        self.checkBox4 = QCheckBox(self.groupBox12)
        self.checkBox4.setObjectName(u"checkBox4")
        self.checkBox4.setGeometry(QRect(10, 20, 41, 16))
        self.groupBox14 = QGroupBox(self.centralwidget)
        self.groupBox14.setObjectName(u"groupBox14")
        self.groupBox14.setGeometry(QRect(480, 360, 71, 61))
        self.comboBox6 = QComboBox(self.groupBox14)
        self.comboBox6.setObjectName(u"comboBox6")
        self.comboBox6.setGeometry(QRect(10, 20, 51, 21))
        self.groupBox15 = QGroupBox(self.centralwidget)
        self.groupBox15.setObjectName(u"groupBox15")
        self.groupBox15.setGeometry(QRect(560, 360, 71, 61))
        self.comboBox7 = QComboBox(self.groupBox15)
        self.comboBox7.setObjectName(u"comboBox7")
        self.comboBox7.setGeometry(QRect(10, 20, 51, 21))
        self.groupBox16 = QGroupBox(self.centralwidget)
        self.groupBox16.setObjectName(u"groupBox16")
        self.groupBox16.setGeometry(QRect(640, 360, 71, 61))
        self.comboBox8 = QComboBox(self.groupBox16)
        self.comboBox8.setObjectName(u"comboBox8")
        self.comboBox8.setGeometry(QRect(10, 20, 51, 21))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 782, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MIIL DETECTION", None))
        self.groupBox1.setTitle(QCoreApplication.translate("MainWindow", u"MODE", None))
        self.pushButton1.setText(QCoreApplication.translate("MainWindow", u"START", None))
        self.pushButton2.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.groupBox4.setTitle(QCoreApplication.translate("MainWindow", u"THRESHOLD", None))
        self.groupBox9.setTitle(QCoreApplication.translate("MainWindow", u"MODEL FILE", None))
        self.pushButton6.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.groupBox10.setTitle(QCoreApplication.translate("MainWindow", u"WEIGHT FILE", None))
        self.pushButton7.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.groupBox3.setTitle(QCoreApplication.translate("MainWindow", u"SETTING", None))
        self.pushButton4.setText(QCoreApplication.translate("MainWindow", u"SAVE STATE", None))
        self.pushButton3.setText(QCoreApplication.translate("MainWindow", u"LOAD STATE", None))
        self.groupBox8.setTitle(QCoreApplication.translate("MainWindow", u"LABEL FILE", None))
        self.pushButton5.setText(QCoreApplication.translate("MainWindow", u"OPEN", None))
        self.groupBox5.setTitle(QCoreApplication.translate("MainWindow", u"VIDEO SIZE", None))
        self.groupBox2.setTitle(QCoreApplication.translate("MainWindow", u"TRIM", None))
        self.label1.setText(QCoreApplication.translate("MainWindow", u"X :", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Y :", None))
        self.checkBox1.setText("")
        self.pushButton8.setText(QCoreApplication.translate("MainWindow", u"CLEAR", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"W :", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"H :", None))
        self.groupBox6.setTitle(QCoreApplication.translate("MainWindow", u"CAMERA ", None))
        self.groupBox7.setTitle(QCoreApplication.translate("MainWindow", u"SENSOR", None))
        self.checkBox2.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.groupBox11.setTitle(QCoreApplication.translate("MainWindow", u"OUTPUT NAME", None))
        self.pushButton9.setText(QCoreApplication.translate("MainWindow", u"ADD", None))
        self.pushButton10.setText(QCoreApplication.translate("MainWindow", u"DELITE", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"NAME :", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"OUTPUT :", None))
        self.groupBox13.setTitle(QCoreApplication.translate("MainWindow", u"RESIZE", None))
        self.checkBox3.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.groupBox12.setTitle(QCoreApplication.translate("MainWindow", u"PIC", None))
        self.checkBox4.setText(QCoreApplication.translate("MainWindow", u"ON", None))
        self.groupBox14.setTitle(QCoreApplication.translate("MainWindow", u"CAM_PIPE", None))
        self.groupBox15.setTitle(QCoreApplication.translate("MainWindow", u"FPS", None))
        self.groupBox16.setTitle(QCoreApplication.translate("MainWindow", u"DET SIZE", None))
    # retranslateUi

